project:
  type: website
  resources:
    - CNAME
  output-dir: _site

website:
  title: "IPNI Lab"
  description: "Integrative and Precision Neuroimaging Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - text: Lab Info
            href: lab.qmd 
          - text: "People"
            href: people.qmd
      - text: Research
        menu:
          - text: "Projects"
            href: projects.qmd
          - text: "Funding"
            href: funding.qmd
          - text: "Publications"
            href: publications.qmd
      - href: data.qmd
        text: Data
      - href: tools.qmd
        text: Tools
    right:
      - icon: github
        href: https://github.com/muet0005
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


